### ISSUE TITLE
Do you accept PRs?

### ISSUE THREAD

**Issue by IonicaBizau** [Tiehuis/Snake#1]
I downloaded this repo and compiled the project on raspberry pi. :smile: Dude, it's awesome!

I fixed few things:
- make the vertical move speed lower (because of the terminal font size) which means that the user will have the impression it's the same speed
- make the init speed lower (`100000`) -- if you don't agree I will not submit it. I needed this change because of fps values of my lcd screen. :tv: 

Nice project! :dizzy:

**Comment by tiehuis** [comment]
This particular project is fairly abandoned, but I'll happily accept any PR's if they make sense and make the experience a little better. The changes you have suggested are fair and I would most likely accept them.

Sorry for the slow reply.

**Comment by IonicaBizau** [comment]
@Tiehuis _Stable_ doesn't mean _abandoned_. :smile: Glad you merged my little changes. It shows to the world that this project is still maintained. :dizzy:
